window.MENU_SOURCE = "https://www.tasteofindia-neuenstadt.de/ordering/?restaurant_uid=da7d834d-5d62-46ad-9831-f51eb8e73381";

window.MENU_CATEGORIES = [
  ["starters", "Warme Vorspeisen", "Warm starters"],
  ["salads", "Salate", "Salads"],
  ["sides", "Beilagen", "Sides"],
  ["naan", "Frisch gebackenes Naan", "Fresh baked naan"],
  ["tandoor", "Tandoori Khajana", "Tandoori treasures"],
  ["chicken", "Vom Huhn", "Chicken"],
  ["lamb", "Vom Lamm", "Lamb"],
  ["vegetarian", "Vegetarische Spezialitäten", "Vegetarian specialties"],
  ["seafood", "Fisch & Garnelen", "Fish & prawns"],
  ["duck", "Duck Specials", "Duck specials"],
  ["biryani", "Biryani-Reis", "Biryani rice"],
  ["kids", "Für unsere kleinen Gäste", "For kids"],
  ["desserts", "Desserts & Eis", "Desserts & ice cream"],
  ["lassi", "Lassi Specials", "Lassi specials"]
].map(([id, label, labelEn]) => ({ id, label, labelEn }));

window.MENU_ITEMS = [
  ["334", "starters", "Onion Ringe Pakora", 6.5, "Knusprige Zwiebelringe im Kichererbsenteig, frisch frittiert und ideal zum Teilen.", "onion-ringe-pakora"],
  ["335", "starters", "Fish Pakora", 8.5, "Zarte Fischstücke in würzigem Kichererbsenteig, goldbraun ausgebacken.", "fish-pakora"],
  ["336", "starters", "Mushroom Pakora", 6.5, "Champignons im aromatischen Pakora-Teig mit feinen indischen Gewürzen.", "mushroom-pakora"],
  ["337", "starters", "Gobhi Pakora", 6.5, "Blumenkohlröschen im Kichererbsenteig, außen knusprig und innen zart.", "gobhi-pakora"],
  ["338", "starters", "Malkatani Suppe", 6.5, "Wärmende indische Suppe mit Gemüse, Gewürzen und leichter Curry-Note.", "malkatani-suppe"],
  ["339", "starters", "Chicken Suppe", 6.0, "Aromatische Hühnersuppe nach indischer Art, leicht, würzig und frisch.", "chicken-suppe"],
  ["340", "starters", "Chicken Pakora", 7.5, "Saftige Hähnchenstücke in Kichererbsenteig, knusprig frittiert.", "chicken-pakora"],
  ["341", "starters", "Chicken Tikka", 7.0, "Mariniertes Hähnchen aus dem Tandoor mit rauchiger Gewürznote.", "chicken-tikka-starter"],
  ["342", "starters", "Paneer Pakora", 7.0, "Hausgemachter indischer Käse im goldenen Pakora-Mantel.", "paneer-pakora"],
  ["343", "starters", "Vegetable Pakora", 6.0, "Gemischtes Gemüse im Kichererbsenteig, frisch und knusprig serviert.", "vegetable-pakora"],
  ["344", "starters", "Jheenga Pakora", 8.0, "Garnelen im würzigen Pakora-Teig, außen kross und innen saftig.", "jheenga-pakora"],
  ["345", "starters", "Vegetable Samosa", null, "Gefüllte Teigtaschen mit Gemüse und Gewürzen. Aktuell als ausverkauft markiert.", "vegetable-samosa", true],
  ["346", "starters", "Gemischte Pakora", 11.0, "Eine Auswahl verschiedener Pakora-Spezialitäten für den gemeinsamen Start.", "gemischte-pakora"],
  ["347", "starters", "Jhinga Suppe", 7.0, "Feine Garnelensuppe mit indischen Gewürzen und aromatischer Brühe.", "jhinga-suppe"],
  ["348", "starters", "Dal Suppe", 5.5, "Cremige Linsensuppe mit Kreuzkümmel, Ingwer und Koriander.", "dal-suppe"],
  ["284", "salads", "Gemischter Salat", 9.0, "Frischer gemischter Salat mit knackigem Gemüse und leichtem Dressing.", "gemischter-salat"],
  ["285", "salads", "Kleiner Gemischter Salat", 7.0, "Kleine Portion frischer Salat als leichte Vorspeise oder Beilage.", "kleiner-gemischter-salat"],
  ["349", "sides", "Kheera Raita", 3.5, "Kühlender Joghurt mit Gurke, Gewürzen und frischen Kräutern.", "kheera-raita"],
  ["350", "sides", "Mixed Raita", 4.0, "Joghurtbeilage mit Gemüse, Kräutern und feinen Gewürzen.", "mixed-raita"],
  ["351", "naan", "Papadam", 3.0, "Dünne, knusprige Linsenfladen als leichter Start oder Beilage.", "papadam"],
  ["352", "naan", "Tandoori Roti", 3.0, "Rustikales Vollkorn-Fladenbrot, frisch im Tandoor gebacken.", "tandoori-roti"],
  ["353", "naan", "Naan", 3.5, "Weiches indisches Fladenbrot, frisch gebacken und klassisch serviert.", "naan"],
  ["354", "naan", "Garlic Naan", 4.0, "Frisches Naan mit Knoblauch, Butter und Kräutern.", "garlic-naan"],
  ["355", "naan", "Chili Naan", 4.0, "Fladenbrot mit Chili für alle, die es etwas schärfer mögen.", "chili-naan"],
  ["356", "naan", "Keema Naan", 4.5, "Gefülltes Naan mit würzigem Hackfleisch und Tandoor-Aroma.", "keema-naan"],
  ["357", "naan", "Paneer Naan", 4.5, "Gefülltes Naan mit mildem indischem Käse.", "paneer-naan"],
  ["358", "naan", "Namaste Naan", 4.5, "Haus-Spezial-Naan mit aromatischer Füllung und frischer Butter.", "namaste-naan"],
  ["359", "naan", "Veggie Naan", 4.5, "Naan mit vegetarischer Füllung, direkt aus dem Tandoor.", "veggie-naan"],
  ["360", "tandoor", "Chicken Tikka (Garlic)", 19.5, "Hähnchenstücke aus dem Tandoor mit Knoblauchmarinade, Paprika und Zwiebeln.", "chicken-tikka-garlic"],
  ["361", "tandoor", "Chicken Tikka Tandoori", 18.5, "Klassisch mariniertes Hähnchen, rauchig im Lehmofen gegrillt.", "chicken-tikka-tandoori"],
  ["362", "tandoor", "Jhinga Tandoori", 23.5, "Garnelen aus dem Tandoor mit würziger Marinade und frischen Kräutern.", "jhinga-tandoori"],
  ["363", "tandoor", "Paneer Tikka Tandoori", 20.0, "Paneerwürfel aus dem Tandoor mit Paprika, Zwiebeln und Masala-Marinade.", "paneer-tikka-tandoori"],
  ["364", "tandoor", "Lamm Tikka Tandoori", 23.0, "Zarte Lammstücke aus dem Lehmofen mit kräftigen Gewürzen.", "lamm-tikka-tandoori"],
  ["365", "tandoor", "Tandoori Mix Grill", 24.5, "Gemischter Grillteller mit verschiedenen Tandoori-Spezialitäten.", "tandoori-mix-grill"],
  ["366", "tandoor", "Haryali Malai Tikka Tandoori", 20.5, "Cremig-grün mariniertes Hähnchen mit Minze, Koriander und mildem Tandoor-Aroma.", "haryali-malai-tikka-tandoori"],
  ["368", "tandoor", "Seek Kebab", 23.5, "Würzige Lamm-Hackspieße aus dem Tandoor, saftig gegrillt.", "seek-kebab"],
  ["369", "tandoor", "Taste of India Grill", 21.5, "Haus-Grillspezialität mit ausgewählten Tandoori-Komponenten.", "taste-of-india-grill"],
  ["367", "tandoor", "Fisch Tikka Tandoori", 23.5, "Marinierter Fisch aus dem Tandoor mit Zitrus, Gewürzen und Kräutern.", "fisch-tikka-tandoori"],
  ["370", "chicken", "Butter Chicken", 16.0, "Zartes Hähnchen in cremiger Tomaten-Butter-Sauce mit feiner Cashewnote.", "butter-chicken"],
  ["371", "chicken", "Chicken Korma", 16.0, "Mildes Hähnchencurry mit Sahne, Nüssen und aromatischen Gewürzen.", "chicken-korma"],
  ["372", "chicken", "Chicken Mango", 16.0, "Hähnchen in fruchtig-cremiger Mango-Curry-Sauce.", "chicken-mango"],
  ["373", "chicken", "Chicken Curry", 14.0, "Klassisches Hähnchencurry mit Tomaten, Zwiebeln und Hausgewürzen.", "chicken-curry"],
  ["374", "chicken", "Chicken Vindaloo", 15.0, "Scharfes Hähnchencurry nach Vindaloo-Art mit Chili und Gewürzen.", "chicken-vindaloo"],
  ["375", "chicken", "Chicken Karahi", 15.0, "Hähnchen in kräftiger Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "chicken-karahi"],
  ["376", "chicken", "Chicken Tikka Masala", 16.0, "Gegrilltes Hähnchen in cremig-würziger Masala-Sauce.", "chicken-tikka-masala"],
  ["377", "chicken", "Chicken Jalfrezi", 16.0, "Hähnchen mit Paprika, Zwiebeln und pikanter Jalfrezi-Sauce.", "chicken-jalfrezi"],
  ["378", "chicken", "Chicken Palak", 15.5, "Hähnchen in cremigem Spinatcurry mit Knoblauch und Gewürzen.", "chicken-palak"],
  ["379", "chicken", "Chili Chicken", 15.5, "Würziges Hähnchen mit Chili, Paprika und aromatischer Sauce.", "chili-chicken"],
  ["380", "chicken", "Chicken Madras", 15.5, "Südindisch inspiriertes Hähnchencurry mit Chili, Kokos und Curryblättern.", "chicken-madras"],
  ["381", "chicken", "Chicken Dhansak", 16.0, "Hähnchen in kräftiger Linsen-Curry-Sauce mit süß-säuerlicher Note.", "chicken-dhansak"],
  ["382", "chicken", "Chicken Sabji", 15.5, "Hähnchen mit gemischtem Gemüse in würziger Curry-Sauce.", "chicken-sabji"],
  ["386", "chicken", "Chicken Nilgiri", 15.0, "Grünes Hähnchencurry mit Kräutern, Kokos und südindischen Gewürzen.", "chicken-nilgiri"],
  ["387", "chicken", "Chicken Lawaabdaar", 15.5, "Hähnchen in reichhaltiger, samtiger Sauce mit Tomaten und Gewürzen.", "chicken-lawaabdaar"],
  ["388", "chicken", "Tawaa Chicken", 16.0, "Hähnchen von der heißen Platte mit kräftiger Masala-Sauce.", "tawaa-chicken"],
  ["389", "lamb", "Lamm Bhindi", 18.0, "Lamm mit Okra in würziger Tomaten-Zwiebel-Masala-Sauce.", "lamm-bhindi"],
  ["390", "lamb", "Lamm Korma", 18.0, "Mildes Lammcurry mit Sahne, Nüssen und feinen Gewürzen.", "lamm-korma"],
  ["391", "lamb", "Lamm Curry", 17.0, "Klassisches Lammcurry mit kräftiger Sauce und Hausgewürzen.", "lamm-curry"],
  ["392", "lamb", "Lamm Karahi", 17.5, "Lamm in Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "lamm-karahi"],
  ["393", "lamb", "Lamm Tikka Masala", 18.5, "Lammstücke in cremig-würziger Tikka-Masala-Sauce.", "lamm-tikka-masala"],
  ["394", "lamb", "Lamm Madras", 17.5, "Würziges Lammcurry nach Madras-Art mit südindischer Note.", "lamm-madras"],
  ["395", "lamb", "Lamm Palak", 17.5, "Lamm in cremigem Spinatcurry mit aromatischen Gewürzen.", "lamm-palak"],
  ["396", "lamb", "Lamm Vindaloo", 17.5, "Scharfes Lammcurry nach Vindaloo-Art mit Chili und Gewürzen.", "lamm-vindaloo"],
  ["397", "lamb", "Lamm Nilgiri", 18.0, "Grünes Lammcurry mit Kräutern, Kokos und Gewürzen.", "lamm-nilgiri"],
  ["398", "lamb", "Lamm Dhansak", 18.0, "Lamm in würziger Linsen-Curry-Sauce mit ausgewogener Süße und Säure.", "lamm-dhansak"],
  ["399", "lamb", "Lamm Sabji", 18.0, "Lamm mit gemischtem Gemüse in aromatischer Curry-Sauce.", "lamm-sabji"],
  ["400", "vegetarian", "Vegetable Korma", 15.0, "Gemüse in milder, cremiger Korma-Sauce mit Nüssen und Gewürzen.", "vegetable-korma"],
  ["401", "vegetarian", "Daal Makhani", 14.5, "Schwarze Linsen langsam gekocht mit Butter, Sahne und Gewürzen.", "daal-makhani"],
  ["402", "vegetarian", "Daal Tarka", 14.0, "Gelbe Linsen mit aromatischem Tarka aus Kreuzkümmel, Knoblauch und Chili.", "daal-tarka"],
  ["403", "vegetarian", "Mix Vegetable", 14.5, "Gemischtes Gemüse in klassischer indischer Curry-Sauce.", "mix-vegetable"],
  ["404", "vegetarian", "Aloo Chana Masala", 14.0, "Kartoffeln und Kichererbsen in würziger Masala-Sauce.", "aloo-chana-masala"],
  ["405", "vegetarian", "Palak Paneer", 15.5, "Paneer in cremigem Spinatcurry mit Knoblauch und Gewürzen.", "palak-paneer"],
  ["406", "vegetarian", "Karahi Paneer", 16.0, "Paneer in kräftiger Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "karahi-paneer"],
  ["407", "vegetarian", "Chili Paneer", 16.0, "Paneer mit Chili, Paprika und würziger Indo-Chinese-Sauce.", "chili-paneer"],
  ["408", "vegetarian", "Aloo Matter Paneer", 14.5, "Kartoffeln, Erbsen und Paneer in aromatischer Curry-Sauce.", "aloo-matter-paneer"],
  ["409", "vegetarian", "Aloo Palak", 14.0, "Kartoffeln in cremigem Spinatcurry mit indischen Gewürzen.", "aloo-palak"],
  ["410", "vegetarian", "Vegetarian Kofta (mild)", 15.5, "Milde Gemüsebällchen in cremiger Curry-Sauce.", "vegetarian-kofta"],
  ["411", "vegetarian", "Paneer Butter Masala", 16.5, "Paneer in samtiger Tomaten-Butter-Masala-Sauce.", "paneer-butter-masala"],
  ["412", "vegetarian", "Bhindi Masala", 16.5, "Okra in Tomaten-Zwiebel-Masala mit Gewürzen.", "bhindi-masala"],
  ["413", "vegetarian", "Aloo Gobhi", 15.5, "Kartoffeln und Blumenkohl mit Kurkuma, Kreuzkümmel und Masala.", "aloo-gobhi"],
  ["414", "vegetarian", "Karahi Mushroom", 14.5, "Champignons in Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "karahi-mushroom"],
  ["415", "seafood", "Jheenga Korma (mild)", 18.5, "Garnelen in milder Korma-Sauce mit Sahne, Nüssen und Gewürzen.", "jheenga-korma"],
  ["416", "seafood", "Jheenga Mango (mild)", 18.5, "Garnelen in fruchtig-cremiger Mango-Curry-Sauce.", "jheenga-mango"],
  ["417", "seafood", "Jheenga Curry", 17.5, "Garnelen in klassischer Curry-Sauce mit Tomaten und Zwiebeln.", "jheenga-curry"],
  ["418", "seafood", "Jheenga Karahi", 18.5, "Garnelen in kräftiger Karahi-Sauce mit Paprika und Ingwer.", "jheenga-karahi"],
  ["419", "seafood", "Jheenga Chili", 18.5, "Garnelen mit Chili, Paprika und würziger Sauce.", "jheenga-chili"],
  ["420", "seafood", "Jheenga Palak", 18.5, "Garnelen in cremigem Spinatcurry.", "jheenga-palak"],
  ["421", "seafood", "Jheenga Madras", 18.5, "Garnelen in würziger Madras-Sauce mit südindischer Note.", "jheenga-madras"],
  ["422", "seafood", "Jheenga Vindaloo", 18.5, "Scharfes Garnelencurry nach Vindaloo-Art.", "jheenga-vindaloo"],
  ["423", "seafood", "Jheenga Masal", 18.5, "Garnelen in kräftiger Masala-Sauce mit Tomaten und Gewürzen.", "jheenga-masal"],
  ["424", "seafood", "Fish Karahi", 18.5, "Fisch in Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "fish-karahi"],
  ["425", "seafood", "Fish Madras", 18.5, "Fischcurry nach Madras-Art mit Chili, Kokos und Curryblättern.", "fish-madras"],
  ["426", "duck", "Ente Butter", 20.0, "Knusprige Ente in cremiger Tomaten-Butter-Sauce.", "ente-butter"],
  ["427", "duck", "Ente Korma", 20.0, "Knusprige Ente in milder Korma-Sauce mit Nüssen und Sahne.", "ente-korma"],
  ["428", "duck", "Ente Mango", 20.0, "Knusprige Ente in fruchtig-cremiger Mango-Curry-Sauce.", "ente-mango"],
  ["429", "duck", "Ente Karahi", 19.0, "Knusprige Ente in Karahi-Sauce mit Paprika, Zwiebeln und Ingwer.", "ente-karahi"],
  ["430", "duck", "Ente Vindaloo", 19.0, "Knusprige Ente in scharfer Vindaloo-Sauce.", "ente-vindaloo"],
  ["431", "duck", "Ente Tikka Masala", 20.0, "Knusprige Ente in cremig-würziger Tikka-Masala-Sauce.", "ente-tikka-masala"],
  ["432", "duck", "Ente Palak", 18.5, "Knusprige Ente in cremigem Spinatcurry.", "ente-palak"],
  ["433", "duck", "Ente Sabji", 18.5, "Knusprige Ente mit gemischtem Gemüse in Curry-Sauce.", "ente-sabji"],
  ["434", "duck", "Ente Dhansak", 19.0, "Knusprige Ente in würziger Linsen-Curry-Sauce.", "ente-dhansak"],
  ["435", "duck", "Ente Chana", 18.5, "Knusprige Ente mit Kichererbsen in Masala-Sauce.", "ente-chana"],
  ["436", "duck", "Ente Curry", 19.0, "Knusprige Ente in klassischer indischer Curry-Sauce.", "ente-curry"],
  ["437", "duck", "Ente Bhindi", 19.5, "Knusprige Ente mit Okra in Tomaten-Zwiebel-Masala.", "ente-bhindi"],
  ["438", "duck", "Ente Madras", 19.0, "Knusprige Ente in würziger Madras-Sauce.", "ente-madras"],
  ["440", "biryani", "Chicken Biryani", 15.5, "Aromatischer Basmatireis mit Hähnchen, Safran, Röstzwiebeln und Gewürzen.", "chicken-biryani"],
  ["441", "biryani", "Taste of India Biryani", 18.0, "Haus-Biryani mit ausgewählten Zutaten, Basmatireis und feinen Gewürzen.", "taste-of-india-biryani"],
  ["442", "biryani", "Vegetable Biryani", 15.0, "Vegetarisches Biryani mit Gemüse, Safranreis und Kräutern.", "vegetable-biryani"],
  ["443", "biryani", "Chicken Tikka Biryani", 18.0, "Biryani mit gegrilltem Chicken Tikka, Basmatireis und Gewürzen.", "chicken-tikka-biryani"],
  ["444", "biryani", "Hyderabadi Biryani", 18.0, "Hyderabadi-Biryani mit geschichtetem Reis, Gewürzen und aromatischer Marinade.", "hyderabadi-biryani"],
  ["200", "kids", "Pommes", 5.5, "Goldene, knusprige Pommes für unsere kleinen Gäste.", "pommes"],
  ["225", "kids", "Chicken Nuggets mit Pommes", 10.0, "Knusprige Chicken Nuggets mit Pommes und Dips.", "chicken-nuggets-mit-pommes"],
  ["328", "desserts", "Mango Creme", 4.5, "Cremiges Mango-Dessert mit fruchtiger Süße.", "mango-creme"],
  ["325", "desserts", "Matka Kulfi", 7.5, "Traditionelles indisches Eis im Matka-Stil mit Nüssen und Safran.", "matka-kulfi"],
  ["326", "desserts", "Indian Paradise", 4.5, "Süßes Dessert im indischen Stil mit Frucht, Creme und Nüssen.", "indian-paradise"],
  ["327", "desserts", "Gulab Jamun", 5.0, "Warme Milchbällchen in Sirup, mit Pistazien und Rosenaroma.", "gulab-jamun"],
  ["495", "lassi", "Namkeen Lassi", 4.0, "Salziger Joghurt-Drink mit Gewürzen, kühl und erfrischend.", "namkeen-lassi"],
  ["496", "lassi", "Sweet Lassi", 4.0, "Süßer, cremiger Joghurt-Drink mit sanfter Kardamomnote.", "sweet-lassi"],
  ["497", "lassi", "Mango Lassi", 4.0, "Cremiger Joghurt-Drink mit Mango, frisch und fruchtig.", "mango-lassi"],
  ["498", "lassi", "Masala Lassi", 4.0, "Gewürzter Joghurt-Drink mit Masala, Kreuzkümmel und Kräutern.", "masala-lassi"],
  ["499", "lassi", "Kokos Lassi", 4.0, "Cremiger Joghurt-Drink mit Kokos und milder Süße.", "kokos-lassi"]
].map(([id, category, name, price, description, slug, soldOut = false]) => ({
  id,
  category,
  name,
  price,
  description,
  slug,
  image: `assets/menu/${slug}.jpg`,
  soldOut
}));
